/*
 * Copyright 2026 GBEMIRO.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.github.gbenroscience.parser.turbo;

/**
 *
 * @author GBEMIRO
 * Functional interface for turbo-compiled expressions.
 * Generated bytecode implements this directly.
 */
@FunctionalInterface
public interface FastExpression {
    /**
     * Evaluate expression with given variable values.
     * 
     * @param variables array of variable values (index corresponds to variable slot)
     * @return result of expression evaluation
     */
    double apply(double[] variables);
}